"use client";

import { useEffect, useState, type ReactNode } from "react";

const Icon = ({ symbol = "•" }: { symbol?: string }) => <span aria-hidden="true" style={{fontWeight:800}}>{symbol}</span>;
const ArrowLeft = () => <Icon symbol="←"/>; const ArrowRight = () => <Icon symbol="→"/>;
const Check = () => <Icon symbol="✓"/>; const Shield = () => <Icon symbol="◆"/>;
const Volume2 = () => <Icon symbol="◖"/>; const Users = () => <Icon symbol="●●"/>;
const AlertTriangle = () => <Icon symbol="!"/>; const MessageCircle = () => <Icon symbol="○"/>;
const Eye = () => <Icon symbol="◉"/>; const Lock = () => <Icon symbol="▣"/>; const RotateCcw = () => <Icon symbol="↻"/>;

type Step = { eyebrow: string; title: string; subtitle?: string; content: ReactNode };

const Card = ({ icon, title, children, tone = "blue" }: { icon?: ReactNode; title: string; children: ReactNode; tone?: "blue" | "gold" | "green" | "red" }) => (
  <article className={`info-card tone-${tone}`}>
    {icon && <div className="card-icon">{icon}</div>}
    <h3>{title}</h3><div className="card-copy">{children}</div>
  </article>
);

export default function Home() {
  const [step, setStep] = useState(0);
  const [answers, setAnswers] = useState<Record<number, number>>({});
  const [submitted, setSubmitted] = useState(false);
  const [checked, setChecked] = useState<Record<string, boolean>>({});
  useEffect(() => { window.scrollTo({ top: 0, behavior: "smooth" }); }, [step]);
  const questions = [
    { q: "Una persona eleva la voz porque no puede ingresar. ¿Cuál es la mejor primera respuesta?", options: ["Responder con el mismo tono", "Escuchar y reconocer su molestia", "Amenazar con retirarla"], a: 1 },
    { q: "¿Qué significa reconocer la emoción de una persona?", options: ["Aceptar cualquier conducta", "Ceder ante su petición", "Mostrar que comprendemos cómo se siente"], a: 2 },
    { q: "¿Cuándo debe detenerse el diálogo?", options: ["Cuando la persona hace una pregunta", "Cuando existen amenazas o riesgo de agresión", "Cuando el procedimiento tarda"], a: 1 },
    { q: "¿Qué combina la técnica práctica del curso?", options: ["Escucha + límite + opción", "Orden + amenaza + sanción", "Silencio + distancia + retirada"], a: 0 },
    { q: "¿Cuál frase ayuda a desescalar?", options: ["Aquí mando yo", "No me importa", "Lo que sí puedo hacer es…"], a: 2 },
  ];
  const score = questions.reduce((n, q, i) => n + (answers[i] === q.a ? 1 : 0), 0);
  const steps: Step[] = [
    { eyebrow: "Capacitación · Agosto 2026", title: "Manejo de conflictos y comunicación asertiva", subtitle: "Prevenir · Desescalar · Comunicar · Actuar profesionalmente", content: <div className="hero-grid"><div className="hero-statement"><span>La meta no es ganar una discusión.</span><strong>Es mantener el control profesional y reducir riesgos.</strong></div><div className="course-map"><p>Al finalizar podrás:</p>{["Reconocer señales tempranas de tensión", "Comunicar límites con respeto", "Aplicar escucha activa y ofrecer opciones", "Decidir cuándo solicitar apoyo"].map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span></div>)}</div></div> },
    { eyebrow: "01 · Tu función", title: "El papel del guardia ante un conflicto", subtitle: "Tu presencia puede evitar que una situación pequeña se convierta en un riesgo.", content: <div className="card-grid three"><Card tone="green" icon={<Eye/>} title="Prevenir">Detecta señales de tensión antes de que el problema crezca.</Card><Card icon={<Volume2/>} title="Desescalar">Baja la intensidad mediante tono, escucha, distancia y opciones.</Card><Card tone="red" icon={<Shield/>} title="Proteger">Si aumenta el riesgo, prioriza seguridad, apoyo y protocolo.</Card></div> },
    { eyebrow: "02 · Entender el origen", title: "¿Qué provoca los conflictos?", subtitle: "Identificar la causa ayuda a responder sin tomar el enojo como algo personal.", content: <div className="cause-list">{[[Lock,"Acceso y restricciones","Rechazo a controles o reglas"],[Users,"Esperas y filas","Frustración por retrasos"],[MessageCircle,"Quejas","Percepción de trato injusto"],[AlertTriangle,"Incidentes","Pérdidas, daños o incumplimientos"],[Volume2,"Personas alteradas","Estrés, enojo o intoxicación"],[Users,"Conflictos entre terceros","Clientes, personal o proveedores"]].map(([I,t,d]:any)=><div key={t}><I/><span><strong>{t}</strong><small>{d}</small></span></div>)}</div> },
    { eyebrow: "03 · Anticiparte", title: "Detecta el escalamiento", subtitle: "Observa cambios en la voz, el cuerpo, la distancia y la disposición a escuchar.", content: <div className="signal-layout"><div className="signal-meter"><span>Conversación</span><span>Tensión</span><span>Riesgo</span><i/></div><div className="signal-list">{["Voz más alta o tono desafiante", "Gestos exagerados, señalar o golpear objetos", "Invasión del espacio personal", "Negativa repetida a escuchar", "Movimientos bruscos o puños cerrados"].map((x,i)=><div key={x}><b>{String(i+1).padStart(2,"0")}</b>{x}</div>)}</div><p className="safety-note"><Shield/> Si percibes riesgo: aumenta la distancia, conserva una salida y solicita apoyo.</p></div> },
    { eyebrow: "04 · Elegir cómo responder", title: "Pasiva, agresiva o asertiva", subtitle: "La autoridad profesional se sostiene con claridad, respeto y control emocional.", content: <div className="card-grid three compare"><Card tone="gold" title="Pasiva">Evita el conflicto, cede o no establece límites.</Card><Card tone="red" title="Agresiva">Grita, amenaza, humilla o intenta imponerse.</Card><Card tone="green" title="Asertiva">Es clara, firme, respetuosa y orientada a soluciones.</Card><div className="formula">AUTORIDAD <b>+</b> RESPETO <b>+</b> CONTROL EMOCIONAL</div></div> },
    { eyebrow: "05 · Técnica práctica", title: "Escucha + límite + opción", subtitle: "Primero entiende. Después responde.", content: <div className="technique"><div><b>1</b><h3>Escucha</h3><p>“Entiendo que está molesto por la espera.”</p><small>No interrumpas; pregunta qué ocurrió.</small></div><div><b>2</b><h3>Límite</h3><p>“Necesito que mantengamos un trato respetuoso.”</p><small>Valida la emoción, no la conducta insegura.</small></div><div><b>3</b><h3>Opción</h3><p>“Podemos revisar el caso con mi supervisor.”</p><small>Explica el procedimiento y una alternativa real.</small></div></div> },
    { eyebrow: "06 · Presencia profesional", title: "Tu cuerpo también comunica", subtitle: "Una postura controlada puede reducir tensión antes de pronunciar una palabra.", content: <div className="body-layout"><div className="guard-figure"><div className="head"/><div className="torso"/><span className="space-ring">DISTANCIA SEGURA</span></div><div className="check-lines">{["Postura abierta, firme y profesional", "Manos visibles y movimientos lentos", "Contacto visual natural, sin retar", "Voz baja, estable y clara", "Evita acorralar; conserva una salida"].map(x=><div key={x}><Check/>{x}</div>)}</div></div> },
    { eyebrow: "07 · Palabras que cambian el rumbo", title: "Frases que ayudan y frases que escalan", content: <div className="phrases"><div className="helps"><h3>✓ Sí ayudan</h3>{["Permítame ayudarle a resolverlo.","Entiendo que está molesto.","Voy a explicarle el procedimiento.","Lo que sí puedo hacer es…", "Solicitaré apoyo de mi supervisor."].map(x=><p key={x}>“{x}”</p>)}</div><div className="avoid"><h3>× Evita</h3>{["Aquí mando yo.","Si no le gusta, váyase.","No me importa.","Usted no sabe con quién se mete.","Amenazas, burlas o sarcasmo."].map(x=><p key={x}>“{x}”</p>)}</div></div> },
    { eyebrow: "08 · Mantener el límite", title: "Cuando alguien se niega a cumplir una regla", content: <div className="rule-flow">{["Repite la solicitud con calma", "Explica brevemente la regla", "Expón el beneficio de cooperar", "Indica consecuencias reales", "Ofrece una decisión clara", "Actúa conforme al protocolo"].map((x,i)=><div key={x}><b>{i+1}</b><span>{x}</span></div>)}<blockquote>“El acceso requiere autorización. Podemos verificarla con el responsable del área o esperar aquí mientras la confirmamos.”</blockquote></div> },
    { eyebrow: "09 · Prioridad: seguridad", title: "¿Cuándo dejar de dialogar?", subtitle: "Detente y solicita apoyo cuando la situación deja de ser segura o supera tus facultades.", content: <div className="stop-grid">{["Hay amenazas creíbles o intento de agresión", "Se detecta un arma u objeto peligroso", "Invaden persistentemente el espacio de seguridad", "Existe riesgo para terceros", "El protocolo exige supervisor o autoridad"].map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span></div>)}<p><Shield/> Mantén distancia · Comunica · Activa el protocolo</p></div> },
    { eyebrow: "10 · Ponlo en práctica", title: "Tres escenarios, una misma disciplina", content: <div className="cases">{[["Acceso restringido","Reconoce la molestia, explica el requisito y ofrece verificar la autorización."],["Cliente alterado","No igualar la agresividad. Escucha, establece un límite y ofrece una opción."],["Dos personas discutiendo","Mantén distancia, pide apoyo y separa verbalmente solo si es seguro."]].map(([t,d],i)=><Card key={t} tone={i===1?"gold":i===2?"red":"blue"} title={t}><p>{d}</p><span className="case-prompt">¿Qué dirías en los primeros 10 segundos?</span></Card>)}</div> },
    { eyebrow: "11 · Antes de actuar", title: "Checklist del guardia", subtitle: "Marca cada punto para completar tu repaso.", content: <div className="checklist">{["Mantengo la calma y controlo mi tono", "Escucho antes de responder", "Explico el procedimiento brevemente", "Evito insultos, amenazas y sarcasmo", "Mantengo una distancia segura", "Ofrezco una alternativa dentro de mis facultades", "Sé cuándo solicitar apoyo", "Actúo conforme al protocolo"].map((x,i)=>{const k=`c${i}`;return <button key={k} className={checked[k]?"done":""} onClick={()=>setChecked(v=>({...v,[k]:!v[k]}))}><span>{checked[k]?<Check/>:null}</span>{x}</button>})}</div> },
    { eyebrow: "12 · Evaluación final", title: submitted ? (score >= 4 ? "¡Excelente trabajo!" : "Repasa y vuelve a intentarlo") : "Comprueba lo aprendido", subtitle: submitted ? `Obtuviste ${score} de ${questions.length} respuestas correctas.` : "Selecciona una respuesta en cada pregunta.", content: <div className="quiz">{questions.map((q,i)=><fieldset key={q.q} disabled={submitted}><legend><span>{i+1}</span>{q.q}</legend>{q.options.map((o,j)=><label key={o} className={`${answers[i]===j?"selected":""} ${submitted&&j===q.a?"correct":""} ${submitted&&answers[i]===j&&j!==q.a?"wrong":""}`}><input type="radio" name={`q${i}`} checked={answers[i]===j} onChange={()=>setAnswers(a=>({...a,[i]:j}))}/>{o}</label>)}</fieldset>)}{!submitted?<button className="submit" disabled={Object.keys(answers).length<questions.length} onClick={()=>setSubmitted(true)}>Ver resultado <ArrowRight/></button>:<button className="retry" onClick={()=>{setSubmitted(false);setAnswers({})}}><RotateCcw/> Intentar de nuevo</button>}</div> },
    { eyebrow: "Capacitación completada", title: "Resolver cuando sea posible. Proteger cuando sea necesario.", content: <div className="closing"><blockquote>“La firmeza no requiere gritos.<br/>La autoridad no requiere humillar.<br/>Escuchar no significa ceder.”</blockquote><p>Adapta siempre tus respuestas a los procedimientos del servicio y al marco legal aplicable.</p><button onClick={()=>setStep(0)}><RotateCcw/> Volver al inicio</button></div> },
  ];
  const current = steps[step]; const progress = Math.round((step / (steps.length - 1)) * 100);
  return <main><header><div className="brand"><span><Shield/></span><div><b>HOPLON</b><small>FORMACIÓN PROFESIONAL</small></div></div><div className="progress-wrap"><span>{progress}%</span><div><i style={{width:`${progress}%`}}/></div></div><span className="counter">{String(step+1).padStart(2,"0")} / {steps.length}</span></header><section className="stage"><div className="accent-lines"/><div className="title-block"><p>{current.eyebrow}</p><h1>{current.title}</h1>{current.subtitle&&<h2>{current.subtitle}</h2>}</div><div className="content">{current.content}</div></section><nav><button onClick={()=>setStep(s=>s-1)} disabled={step===0}><ArrowLeft/> Anterior</button><div className="dots">{steps.map((_,i)=><button key={i} aria-label={`Ir a la sección ${i+1}`} className={i===step?"active":i<step?"passed":""} onClick={()=>setStep(i)}/>)}</div><button className="next" onClick={()=>setStep(s=>s+1)} disabled={step===steps.length-1}>Siguiente <ArrowRight/></button></nav></main>;
}
